### ISSUE TITLE
definition duplicate for einwohner and loess_aenderung

### ISSUE THREAD

**Issue by KatharinaLauer** [robert-koch-institut/Abwassersurveillance_AMELAG#1]
![Screenshot 2024-03-19 at 12 37 41](https://github.com/robert-koch-institut/Abwassersurveillance_AMELAG/assets/142669531/1758b23f-46af-4f19-956a-788323992cdd)
Loess_aenderung and einwohner have the same definition - maybe a mistake in the amelag_einzelstandorte Variablen und Variablenausprägungen table? https://github.com/robert-koch-institut/Abwassersurveillance_AMELAG/tree/main?tab=readme-ov-file#variablen-und-variablenauspr%C3%A4gungen

**Comment by HannesWuensche** [comment]
Dear @KatharinaLauer,

thank you for bringing this to our attention. 
We updated the documentation accordingly. 

Best regrads
@HannesWuensche 
RKI | Open Data Team
