### ISSUE TITLE
Missing Data from July 30th, 2024

### ISSUE THREAD

**Issue by damianino1** [robert-koch-institut/Abwassersurveillance_AMELAG#4]
Data is already available on RKI page https://infektionsradar.gesund.bund.de/de/covid/abwasser but metadata from July 30th, 2024 is still no uploaded here.. please provide an update of metadata asap. Thx

**Comment by HannesWuensche** [comment]
Dear @damianino1 

Thank you very much for letting us know. Unfortunately, irregularities sometimes occur.
The data and metadata should be available again.

Best regards,
@HannesWuensche
Team | RKI Open Data
