### ISSUE TITLE
Anpassung der Datensätze am 23.10

### ISSUE THREAD

**Issue by RKIOpenData** [robert-koch-institut/Abwassersurveillance_AMELAG#6]
Liebe Nutzer:innen,

am 23.10.2024. wird es eine Anpassung dieses Datensatzes geben. Hintergrund ist, dass an einigen Kläranlagen seit Oktober 2024 auch Influenzaviren im Abwasser erfasst werden. Das aktualisierte Datenformat spiegelt diese zusätzliche Messungen nun wieder. Die Datensätze enthalten die Messdaten auch rückwirkend, d.h. für den gesamten verfügbaren Messzeitraum.

Konkret werden in den beiden Datensatz-Files neue Spalten hinzugefügt.

An die Datei [`amelag_einzelstandorte.tsv`](https://github.com/robert-koch-institut/Abwassersurveillance_AMELAG/blob/main/amelag_einzelstandorte.tsv) werden folgende Spalten hinzugefügt:

- **normalisierung**: Definiert, ob die Messwerte (nach Durchfluss) normalisiert wurden. Mögliche Werte sind `ja`, `nein`, `NA`
- **typ**: Definiert den gemessenen Virustyp. Mögliche Werte sind `Influenza-A`, `Influenza-B`, `Influenza-Gesamt`, `SARS-CoV-2`.
- **unter_bg**:  definiert ob ein Messwert unterhalb der Bestimmungsgrenze liegt. Mögliche Werte sind `ja`, `nein`, `NA`

An die Datei [`amelag_aggregierte_kurve.tsv`](https://github.com/robert-koch-institut/Abwassersurveillance_AMELAG/blob/main/amelag_aggregierte_kurve.tsv)  werden folgende Spalten hinzugefügt:

- **normalisierung**: Definiert, ob die Messwerte (nach Durchfluss) normalisiert wurden. Mögliche Werte sind `ja`, `nein`, `NA`
- **typ**: Definiert den gemessenen Virustyp. Mögliche Werte sind `Influenza-A`, `Influenza-B`, `Influenza-Gesamt`, `SARS-CoV-2`.

Bitte passen Sie Ihre Analysen entsprechend an das neue Datensatzformat an.

Viele Grüße
Simon | RKI Open Data Team

**Comment by Rutger265** [comment]
Wäre es nicht übersichtlicher, getrennte Dateien für SARS-CoV-2 (wie bisher) und Influenza (neu) zu machen?

**Comment by SimonScholler** [comment]
Lieber Rutger,

danke für den Input - wir denken das ist hier etwas Geschmackssache und auch abhängig vom Use-Case. Ein einfacher Filter auf der kombinierten CSV-Datei macht es schnell genauso übersichtlich. Generell versuchen wir, die Anzahl der Dateien wenn möglich gering zu halten, damit die Dokumentation übersichtlich bleibt.

Viele Grüße
Simon | RKI Open Data Team

**Comment by SimonScholler** [comment]
Update: Die Anpassung der Datensätze ist nun abgeschlossen.
